- name: End to end smoke tests
  hosts: app_servers:database_servers
  gather_facts: true
  become: true
  tags:
    - smoketest
    - smoketest_database
    - smoketest_database_servers
  roles:
    - smoketest_database

- name: End to end smoke tests
  hosts: app_servers
  become: false
  gather_facts: true
  tags:
    - smoketest
    - smoketest_app
    - smoketest_app_servers
  roles:
    - smoketest_app
